//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientRegistration
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        public int p_id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public int Pin { get; set; }
        public string Aadhar_no { get; set; }
        public string Mobile { get; set; }
        public string Blood_group { get; set; }
        public System.DateTime Visit_date { get; set; }
        public string purpose_of_visit { get; set; }
    }
}
